export const styles = {
  page: { minHeight: "100vh", background: "var(--nuage)" },
  header: {
    background: "var(--rouge)",
    color: "#fff",
    padding: "16px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "sticky",
    top: 0,
    zIndex: 10,
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
  },
  headerTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "18px",
    fontWeight: 700,
    letterSpacing: "-0.01em",
  },
  headerActions: { display: "flex", gap: "8px" },
  ghostBtn: {
    background: "rgba(255,255,255,0.15)",
    color: "#fff",
    border: "1px solid rgba(255,255,255,0.35)",
    borderRadius: "8px",
    padding: "6px 12px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  main: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "24px 16px 64px",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: "16px",
  },
  modalBox: {
    background: "var(--papier)",
    borderRadius: "var(--radius)",
    boxShadow: "var(--ombre)",
    padding: "20px",
    maxWidth: "480px",
    width: "100%",
    maxHeight: "85vh",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
  },
  modalTitle: { fontWeight: 700, fontSize: "16px", margin: 0 },
  modalCloseBtn: {
    background: "none",
    border: "none",
    fontSize: "22px",
    lineHeight: 1,
    cursor: "pointer",
    color: "var(--muted)",
    padding: "2px 4px",
    flexShrink: 0,
  },
  fileButton: {
    background: "var(--nuage)",
    border: "2px dashed var(--trait)",
    borderRadius: "8px",
    padding: "22px 16px",
    textAlign: "center",
    cursor: "pointer",
    color: "var(--encre)",
    fontSize: "14px",
    fontWeight: 600,
    width: "100%",
  },
  fileButtonHint: {
    display: "block",
    marginTop: "4px",
    fontSize: "12px",
    fontWeight: 400,
    color: "var(--muted)",
  },
  posteCard: {
    background: "var(--papier)",
    border: "1px solid var(--trait)",
    borderLeft: "4px solid var(--rouge)",
    borderRadius: "var(--radius)",
    boxShadow: "var(--ombre)",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  posteHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "8px",
  },
  posteTitleWrap: { display: "flex", alignItems: "center", gap: "10px" },
  badge: {
    background: "var(--rouge)",
    color: "#fff",
    width: 26,
    height: 26,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: 700,
    flexShrink: 0,
  },
  posteTitle: { fontWeight: 700, fontSize: "15px" },
  posteHeaderActions: { display: "flex", gap: "10px", alignItems: "center" },
  arrowBtn: {
    background: "#fff",
    border: "1px solid var(--trait)",
    borderRadius: "6px",
    width: "28px",
    height: "28px",
    cursor: "pointer",
    color: "var(--encre)",
    fontSize: "13px",
  },
  dangerLink: {
    background: "none",
    border: "none",
    color: "var(--rouge)",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  sectionLabel: {
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--muted)",
    marginBottom: "8px",
  },
  fieldGroup: { display: "flex", flexDirection: "column", gap: "4px" },
  label: { fontSize: "13px", fontWeight: 600, color: "var(--encre)" },
  required: { color: "var(--rouge)" },
  input: {
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "9px 10px",
    fontSize: "14px",
    background: "#fff",
    color: "var(--encre)",
    width: "100%",
  },
  inputInvalide: {
    border: "1px solid var(--rouge)",
    boxShadow: "0 0 0 1px var(--rouge)",
  },
  textarea: {
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "9px 10px",
    fontSize: "13px",
    fontFamily: "ui-monospace, Menlo, monospace",
    background: "#fff",
    color: "var(--encre)",
    width: "100%",
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" },
  fullSpan: { gridColumn: "1 / -1" },
  btnSecondary: {
    background: "#fff",
    border: "1px solid var(--trait)",
    color: "var(--encre)",
    borderRadius: "8px",
    padding: "8px 14px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  btnDashed: {
    background: "transparent",
    border: "2px dashed var(--trait)",
    color: "var(--muted)",
    borderRadius: "var(--radius)",
    padding: "14px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  },
  btnWhatsapp: {
    background: "var(--whatsapp)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "12px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    flex: 1,
  },
  btnDark: {
    background: "var(--encre)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "12px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    flex: 1,
  },
  btnOutlinePrint: {
    background: "#fff",
    border: "1px solid var(--trait)",
    color: "var(--encre)",
    borderRadius: "10px",
    padding: "12px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    flex: 1,
  },
  intervenantRow: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "10px",
    background: "var(--nuage)",
  },
  intervenantMainLine: { display: "flex", gap: "8px", alignItems: "center" },
  conducteurLine: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    fontSize: "13px",
    paddingLeft: "2px",
  },
  removeBtn: {
    background: "#fff",
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    width: "36px",
    height: "36px",
    cursor: "pointer",
    color: "var(--muted)",
    flexShrink: 0,
  },
  addLink: {
    background: "none",
    border: "none",
    color: "var(--rouge)",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
    textAlign: "left",
  },
  apercuBox: {
    background: "var(--nuage)",
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "14px",
    fontSize: "13px",
    whiteSpace: "pre-wrap",
    color: "var(--encre)",
    margin: 0,
    fontFamily: "ui-monospace, Menlo, monospace",
  },
  panel: {
    background: "var(--papier)",
    border: "1px solid var(--trait)",
    borderRadius: "var(--radius)",
    boxShadow: "var(--ombre)",
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  panelTitle: { fontWeight: 700, fontSize: "15px" },
  histItem: {
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "12px",
    background: "var(--nuage)",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  histTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "6px",
  },
  histDate: { fontSize: "11px", color: "var(--muted)" },
  histActions: { display: "flex", gap: "10px", flexWrap: "wrap" },
  linkBtn: {
    background: "none",
    border: "none",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
  },
  modeleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "13px",
  },
  finalBox: { display: "flex", flexDirection: "column", gap: "10px" },
  finalTextarea: {
    width: "100%",
    minHeight: "420px",
    border: "1px solid var(--trait)",
    borderRadius: "var(--radius)",
    padding: "14px",
    fontSize: "13px",
    fontFamily: "ui-monospace, Menlo, monospace",
    background: "#fff",
    color: "var(--encre)",
  },
  actionsRow: { display: "flex", gap: "8px", flexWrap: "wrap" },
  previewBox: {
    border: "1px dashed var(--rouge)",
    borderRadius: "8px",
    padding: "12px",
    background: "#fff5f5",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  searchInput: {
    border: "1px solid var(--trait)",
    borderRadius: "8px",
    padding: "8px 10px",
    fontSize: "13px",
    width: "100%",
  },
  syncBanner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "#fff8e1",
    border: "1px solid #f0c14b",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "13px",
  },
};
